### ISSUE TITLE
Tray bugs

### ISSUE THREAD

**Issue by komitaltrade** [baumgarr/Nixnote2#37] opened 2014-12-13 02:30 UTC
I think that it is not new, but to mention also (fonts in XFCE are horrible).

Tray bugs:
1) It is impossible to set to start hidden (minimized) in tray, as it is minimized (not hidden) and appear in windows list (e.g. on startup). It remain in tray when in tray is ticked hide option.

2) When you tick show in tray, it will not show, rather appear in windows list (again) and you must ot tick on windows list icon to show it.

3) When you than click close (despite checked function to close in tray) it is closed complete (gone from tray).

**Comment by baumgarr** [comment] 2015-03-25 18:28
I can't reproduce this on KDE.  My best guess is that Qt is responding that the system tray icon isn't available via the QSystemTrayIcon::isSystemTrayAvailable().  I added a debug message, so after the next beta you can look for a message saying if it is available.  It should say something like "nixnote.cpp @ 638 ) isSystemTrayAvailable: true "  

If it is returning true, then I'm missing something and am not recreating the bug.

If it is returning false then there isn't anything I can do.  I check this on startup because it can cause confusion if people switch window managers.  If a tray icon isn't available and they have said to minimize or close to the tray, the window vanishes and they can't close it without manually killing the process.

**Comment by komitaltrade** [comment] 2015-03-25 21:08
Sorry, I didn't wrote precise. Machine is x64, DE was XFCE and GNOME and OS was Manjaro. As I found in meantime too much "issues" with Manjaro, I switched to "native" Arch (KDE). Now I'm busy, but I will give you review for KDE Arch x64 next week. 

I will be capable to keep test it in KDE Arch. Intensity of testing depends on stability.(I can send couple of hours per week). However, count just on KDE Arch x64 and if you have some specific instructions what you will like to be "forced" in testing, let me know.

I would like that you get success with project as it is one of the 1st then (inside top five - p.a. m.o.) projects non supported from community, but from essential importance for Linux positioning in desktop market. In fact, all ten are related to "multiplication tasking" (majority of people can not effectively use their mobile devices with Linux desktop).

So, I really want to help you, just let me know how.

**Comment by baumgarr** [comment] 2015-03-25 21:22
If you want to use the latest beta and try to recreate the problem that would be helpful.  I don't think I changed any of that logic (other than a debug statement), so if it is working then it is most probably the isSystemTrayAvailable() function.  Alternatively, you could pull from GitHub & try to do a fresh build, but that is more involved.

Thanks.

**Comment by komitaltrade** [comment] 2015-03-26 06:04
OK. Next week. I will let yo know.

**Comment by komitaltrade** [comment] 2015-04-01 16:58
Bad news.
I'm on "vanila" Arch x64 KDE4.
First I tried QT version and it look horrible (font rendering). Don't keep settings from preferences. Can't see notes at all (it create notes, but what???). Quick note is not possible also to handle (font color is not possible to change) and it is not possible to save (or yes, but it is not possible to be seen).

Than I tried git version and font rendering is OK (completely) and it looks much better and "native" than QT version. But, .... everything else is same.

Please, "pull down" in alpha version as in that way you can get testers (and you need it). With beta, every user will "drop idea" forever. Don't loose users in such of "naive way". Application is worth to keep on it. Concept is just perfect. Look and feel also. You need to fix functionality and soon will be on all "cover pages" like "revolutionary apps".

Keep on. 

If I can do something more, let me know.

**Comment by komitaltrade** [comment] 2015-04-01 17:01
And to not forget.

Yes you changed something. It is now somehow "non-resposive" (don't react prompt on commands). Before, it wasn't case.

**Comment by baumgarr** [comment] 2015-04-01 20:48
I'm glad you find the new fonts easier to use.

I'm not sure I understand what your other problem is?

**Comment by komitaltrade** [comment] 2015-04-02 03:56
Hmmm, after PC restart, most thinks works. I tried in same time also evernote web in chromium and sync worked well. After restar I can add and delete notes, settings are now preserved. Only issue what I note is "text color" and "highlight". As far all others function in toolbar reacts perfect (bold, size, type, formating, clean, undo/redo, ....), just that two "buttons" reacts without control and very late (or don't react at all). Insert files, preview, .right click menu, .. all works fine.

One functionality issue. When I change notebooks, it shows me all notes (from other notebooks) anyway.  It is same with Tags (shows other notes).

**Comment by komitaltrade** [comment] 2015-04-02 03:57
BTW - Why it needed to be restarted PC (maybe logout also works) to "get it in road"?

**Comment by baumgarr** [comment] 2015-04-02 10:05
I have no idea why you would have had to restart unless there was another
copy running.  If you try to run it twice, the first copy will be brought
up and the second will stop.  Maybe you had two running  & were not aware.

The highlight & font color buttons both work for me.  The way they should
work is that a single click will change the current selected text.  If no
text is selected new text should be colored or highlighted.  To change the
color you need to click & hold the button to bring up a menu.  The default
font color is black and the default highlight color is yellow.  Try using
the "View / Source" menu option.  That should show you the HTML that it is
creating.  Maybe that will help find out what the problem is.

Glad everything else is working.

**Comment by komitaltrade** [comment] 2015-04-03 01:35
As I test it on test machine (it mean also test OS), it could be many reasons for issues what I noticed.

As I'm also curious, I done fresh test again (fresh OS and NixNote). I didn't opened that before reboot (I guess that I don't need, as far as I know), but .... double instance is eliminated like cause). I figured how color works, but it was unresponsive (I'm not so sure how functional is solution). Now, I can change it, but yet with "slowmotion". At same time, in calligra words, it is done instantly (leak of my resources).

This is git version, but not java anymore and I guess that problems can not come from compilation (?!?! can it?). So, count that evry time I have 100% new version (I didn't hash packages). Maybe to try precompiled package (pkg.tar.xz) with known final installer hash (from where to download?)?

**Comment by baumgarr** [comment] 2015-04-03 01:48
The latest one that is available as a pre-compiled binary is the beta-2 and
it has some known problems (it is also a year old).  I'm planning on
releasing a beta-3 soon, but I have a few things I need to cleanup first so
it may be as long as a week until it is ready.  When it is available it
will be on SourceForge along with the Java version.

I would think that if you compiled it from scratch and it succeeded you
should be OK, but I guess it is possible that the problem is caused by a
different version of Qt than the one I'm compiling with.

This version actually does have one Java component to encrypt & decrypt
text in a note, but nothing else requires Java.

**Comment by komitaltrade** [comment] 2015-04-03 05:11
One more think ("issue"). I check all options to be closed and minimized in try.

1) On Exit (menu) and/or close button on dialog, app is closed (dissapear from try also).

2) On minimized state, it remain on taskbar (you know, 3-4 cm) and in try.

As far as I have experiance with other apps, on options to "place it in try" it should to be visible just in try (on minimized and closed commands). On taskbar should to appear just when it is "active" (dialog) and not in any other combination.

I don't think that this part depend of compilation, as it acts perfectly (but just as I described) and promptly in numerous attempts.

**Comment by komitaltrade** [comment] 2015-04-03 05:12
Sorry, tray, not try (I'm going to sleep now).

**Comment by komitaltrade** [comment] 2015-04-03 05:22
Before to going to sleep, I get one moment. It change behaviour depends on combinations on preferences (but, not as it should). So, it is "closed" (just e.g.) with only uncheked otion for splash. I check splash also (all cheked), exit app. Start app (no splash), but it is minimized on close. I uncheck, splash again and exit. Start again and it go in tray on "close" (but on minimize stay on taskbar) and so on ....... I'm so tired and I'm not capable to "catch" the rule, but 100% it not maintain same behaviour on same preference options (depends on "steps", but how .....).

**Comment by baumgarr** [comment] 2015-04-03 09:12
I've had other people report tray bugs, but I've never been able to
reproduce them, but I have a theory.

When someone selects the "close to tray" or "minimize to tray" options,
NixNote calls a Qt function to see if the window manager supports tray
icons.  If the function returns false, this request is ignored.  This is
done for safety reasons.  If I don't do this and the window manager doesn't
support tray icons, the program essentially vanishes.  When the user tries
to start it again, they get messages that there is another one running and
they cannot get out of the loop without editing a config dialog.  This is a
problem that has happened several times with the old NixNote.

I think the function is returning "false" and NixNote is ignoring the
request.  There is a way to test if this is happening.  If you go into the
Prefences dialog, switch to the Debug tab, and set the message level to
"Debug".  Next, restart NixNote and look under Help/Message Log.  Look for
a line that says "( nixnote.cpp @ 638 ) isSystemTrayAvailable:".  If it
says "true" then there is a bug somewhere, but if it says "false" then Qt
is saying your window manager doesn't support tray icons and your request
is ignored.

**Comment by komitaltrade** [comment] 2015-07-23 01:23
Now I switched (Arch - x64 - Cinnamon) to your AUR package (from git) called beta (3) and it works now much more better than git version and on KDE. Only I still have same issue. Tray (now in Cinnamon, not KDE) act as Nixnote want and not as it is set in preferences. Sometimes icon not appear at all, sometimes not hide window from taskbar, .... BUT, that is cosmetics (important, but just cosmetics) issues, as Nixnote doing substanital tasks without any error. However, I done some keybindings and it could be in production. Only one question - what is the command to show/hide (in tray right click menu), to assign hotkeys? 

P.S. - Why you didn't assigned hotkeys to right click menu in tray (Evernote have it)???

**Comment by komitaltrade** [comment] 2015-07-23 01:27
P.S. -1 - Maybe to consider to place in Help (message Log above), popup dialog with list of all commands (and/or non/assigned hotkeys), as than user can assign his own hotkeys for any available action?

**Comment by baumgarr** [comment] 2015-07-28 14:17
I (hopefully) have the show/hide & minimize to tray bugs fixed.  Please let me know if there are any issues after the next beta.

There is no hotkey to show/hide the tray icon.  As far as I can tell there is no universal way to do that across window managers.

**Comment by komitaltrade** [comment] 2015-07-29 18:14
Thanks. 
Sorry for my poor English. I didn't asked (recommeded) universal hotkeys, I asked some list of command line actions to assign hot key in my own custom keybindigs (e.g. what I should to place for command to toggle show/hide).

**Comment by baumgarr** [comment] 2015-10-16 16:22
Sorry for the slow response.  I've been busy with other things.

To have custom keybindings you need to copy the shortcuts.txt file from your install directory to your ~/.nixnote/ directory.  It looks for them first and then looks in the install directory.  The settings are hierarchial, so if you don't specify it in your shortcuts.txt it will find them in the install directory shortcuts.txt.

**Closed by baumgarr** 2015-10-16 16:22 UTC
Labels: Distro/Window Manager Specific, Pending User Feedback
