### ISSUE TITLE
Arch Linux libcurl.so.4: version `CURL_OPENSSL_3' not found

### ISSUE THREAD

**Issue by F1nny** [baumgarr/nixnote2#276] opened 2017-02-14 23:21 UTC
Hey guys,
Firstly thanks for creating and maintaining Nixnote - it's friggin amazing and I use it constantly so greatly appreciated! Anyway I've always used it on my desktop and never had issues, around the 4th or 5th I began traveling with my laptop and was in urgent need so nabbed it from the arch linux AUR last week, I have NOT been able to get it started. It reports
nixnote2: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by nixnote2)

I've tried rolling back curl, libcurl-compat, lib32-libcurl-compat, openssl, libpsl, opencv, etc. and just CANT get it figured. The maintainer just said 'it's beta and will maintain stable separately' which I replied asking for help just tracking down and nothing yet, then I realized 2.0 just released (yay congrats!) so swapped to that package nixnote2 on the AUR from the same maintainer which was JUST added to the AUR, but SAME error :( I reported the same error being received to the AUR and hopefully he can assist in getting it figured but because I'm going in circles here and it doesn't APPEAR others are getting the same error I'm hoping you may be able to help me track it down? Any ideas what's up? 

Here's what I tried downgrading in desparation haha, note the timestamps as at some point I re-upgraded then re-downgraded just a few packages later in the day. ANY help would be greatly appreciated, this laptop didn't have libcurl-compat however I did grab the last version off the arch rollback machine/whatever it's called now but that didn't work either. Anyyyyy ideas what I can do to track down?

`[2017-02-14 11:16] [ALPM] downgraded libpsl (0.17.0-1 -> 0.16.1-1)

[2017-02-14 11:53] [ALPM] downgraded nss (3.28.1-1 -> 3.27.2-1)

[2017-02-14 11:55] [ALPM] downgraded openssl (1.0.2.k-1 -> 1.0.2.j-1)

[2017-02-14 11:55] [ALPM] downgraded lib32-openssl (1:1.0.2.k-1 -> 1:1.0.2.j-1)

[2017-02-14 11:55] [ALPM] downgraded openssl (1.0.2.j-1 -> 1.0.2.i-1)

[2017-02-14 11:55] [ALPM] downgraded lib32-openssl (1:1.0.2.j-1 -> 1:1.0.2.i-1)

[2017-02-14 15:13] [ALPM] downgraded opencv (3.2.0-1 -> 3.1.0-7)

[2017-02-14 15:13] [ALPM] downgraded opencv (3.1.0-7 -> 3.1.0-6)

[2017-02-14 15:13] [ALPM] downgraded openssl (1.0.2.k-1 -> 1.0.2.j-1)

[2017-02-14 15:13] [ALPM] downgraded lib32-openssl (1:1.0.2.k-1 -> 1:1.0.2.j-1)

[2017-02-14 15:13] [ALPM] downgraded libpsl (0.17.0-1 -> 0.16.1-1)`

Also worth noting I even tried the package from the archlinuxcn repo, same deal. Thinking must be either a dep of a dep but if no one else experiencing the same then more likely something installed that could be interfering or something? No idea at this point I'm going in circles :(

**Comment by artmg** [comment] 2017-02-15 09:09
Hi @F1nny, so glad you appreciate all the work that has gone into this software. The error you mention sounded familiar so I searched for `curl` in the closed issues and found #245 that mentions a workaround in the comments of the AUR doc page. Please look there and try the suggestions, and report back your progress - thanks.

**Comment by petRUShka** [comment] 2017-02-17 21:19
Workaround is working at the moment.  You should run it like this:
```
env "LD_PRELOAD=libcurl.so.3" nixnote2
```

But is it possible to automate it in nixnote2 binary? Or at the compilation process?

**Comment by artmg** [comment] 2017-02-18 13:16
Hi, AUR package maintainer @mortzprk reports on 2017-02-18 12:41

`nixnote now run without any hacks. just type 'nixnote2' in terminal or run from GUI`

Any AUR users should now update their install to the latest version, where the issue is reportedly fixed. 

Many thanks to mortzprk for his contribution in making this great software more widely available!

**Comment by baumgarr** [comment] 2017-02-20 02:16
Closing as fixed with latest AUR update.

Thanks!

**Closed by baumgarr** 2017-02-20 02:16 UTC
