### ISSUE TITLE
RPM upgrade to nixnote2-2.0_beta5-0.x86_64.rpm fails to produce working nixnote2

### ISSUE THREAD

**Issue by jeffbuhrt** [baumgarr/nixnote2#101] opened 2015-11-24 02:16 UTC
The workaround/fix is to uninstall and reinstall.
[The details & ticket are FYI.]

$ cat /etc/fedora-release 
Fedora release 22 (Twenty Two)

# rpm -Uv nixnote2-2.0_beta5-0.x86_64.rpm 
Preparing packages...
nixnote2-2.0_beta5-0.x86_64
nixnote2-2.0_beta4-0.x86_64
# rpm -qa | grep nixno
nixnote2-2.0_beta5-0.x86_64

$ nixnote2
bash: nixnote2: command not found...

$ rpm -qa nixnote2
nixnote2-2.0_beta5-0.x86_64
[jbuhrt@jtosh ~]$ rpm -qail nixnote2
Name        : nixnote2
Version     : 2.0_beta5
Release     : 0
Architecture: x86_64
Install Date: Mon 23 Nov 2015 08:57:42 PM EST
Group       : Applications/Internet
Size        : 9869669
License     : GPLv2
Signature   : (none)
Source RPM  : nixnote2-2.0_beta5-0.src.rpm
Build Date  : Sun 22 Nov 2015 04:42:04 PM EST
Build Host  : localhost.localdomain
Relocations : (not relocatable)
Packager    : Randy Baumgarte <randy@fbn.cx>
Vendor      : Randy Baumgarte
URL         : http://nevernote.sourceforge.net/
Summary     : An Evernote client clone for Linux
Description :
NixNote:: Evernote client clone for Linux

Copyright 2009-2014, Randy Baumgarte
Licensed under GNU General Public Lisence version 2

This is an incomplete clone of Evernote designed to run on Linux.
While this is designed to work with Evernote, it is in no way
connected with or supported by Evernote.  Any problems you encounter will not be corrected by them
and, since this is GPL software, you are using this software at your own risk.

See release.txt for details of what works and what doesn't work.

Documents:

release.txt:    Includes new features, known bugs and limitations.

changelog.txt:  ChangeLog and development history
install.txt:    Build and install instructions
credit.txt:     Credit of nixnote developers
gpl.txt:        License description of GPL v2.
license.txt:    Legal notices for licenses and trademarks

shortcut_howto.txt:  How-to document to setup shortcut keys.
shurtcut_sample.txt: Its configuration sample

  CFLAGS="${CFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic}" ; export CFLAGS ;
  CXXFLAGS="${CXXFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic}" ; export CXXFLAGS ;
  FFLAGS="${FFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I/usr/lib64/gfortran/modules}" ; export FFLAGS ;
  FCFLAGS="${FCFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I/usr/lib64/gfortran/modules}" ; export FCFLAGS ;
  LDFLAGS="${LDFLAGS:--Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld}"; export LDFLAGS;
  [ "1" = 1 ] && for i in $(find $(dirname ./configure) -name config.guess -o -name config.sub) ; do
      [ -f /usr/lib/rpm/redhat/$(basename $i) ] && /usr/bin/rm -f $i && /usr/bin/cp -fv /usr/lib/rpm/redhat/$(basename $i) $i ;
  done ;
  [ "1" = 1 ] && [ x != "x-specs=/usr/lib/rpm/redhat/redhat-hardened-ld" ] &&
      for i in $(find . -name ltmain.sh) ; do
        /usr/bin/sed -i.backup -e 's~compiler_flags=$~compiler_flags="-specs=/usr/lib/rpm/redhat/redhat-hardened-ld"~' $i
      done ;
  ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu \
	--program-prefix= \
	--disable-dependency-tracking \
	--prefix=/usr \
	--exec-prefix=/usr \
	--bindir=/usr/bin \
	--sbindir=/usr/sbin \
	--sysconfdir=/etc \
	--datadir=/usr/share \
	--includedir=/usr/include \
	--libdir=/usr/lib64 \
	--libexecdir=/usr/libexec \
	--localstatedir=/var \
	--sharedstatedir=/var/lib \
	--mandir=/usr/share/man \
	--infodir=/usr/share/info
sed -i 's|^hardcode_libdir_flag_spec=.*|hardcode_libdir_flag_spec=""|g' libtool
sed -i 's|^runpath_var=LD_RUN_PATH|runpath_var=DIE_RPATH_DIE|g' libtool
/usr/bin/nixnote2
/usr/share/applications/nixnote2.desktop
/usr/share/doc/nixnote2
/usr/share/doc/nixnote2/changelog.Debian.gz
/usr/share/doc/nixnote2/copyright
/usr/share/man/man1/nixnote2.1.gz
/usr/share/nixnote2
/usr/share/nixnote2/README.txt
/usr/share/nixnote2/certs
/usr/share/nixnote2/certs/thawte.pem
/usr/share/nixnote2/certs/verisign_certs.pem
/usr/share/nixnote2/changelog.txt
/usr/share/nixnote2/colors.txt
/usr/share/nixnote2/gpl.txt
/usr/share/nixnote2/help
/usr/share/nixnote2/help/UserDocumentation.odt
/usr/share/nixnote2/help/UserDocumentation.pdf
/usr/share/nixnote2/help/about.html
/usr/share/nixnote2/images
/usr/share/nixnote2/images/alarmclock.png
/usr/share/nixnote2/images/attribute.png
/usr/share/nixnote2/images/black_dot.png
/usr/share/nixnote2/images/bold.png
/usr/share/nixnote2/images/bulletList.png
/usr/share/nixnote2/images/classic-theme
/usr/share/nixnote2/images/classic-theme/home.png
/usr/share/nixnote2/images/classic-theme/left_arrow.png
/usr/share/nixnote2/images/classic-theme/notebook-green.png
/usr/share/nixnote2/images/classic-theme/right_arrow.png
/usr/share/nixnote2/images/classic-theme/stack-green.png
/usr/share/nixnote2/images/classic-theme/synchronize.png
/usr/share/nixnote2/images/classic-theme/windowIcon.png
/usr/share/nixnote2/images/collapsed.png
/usr/share/nixnote2/images/copy.png
/usr/share/nixnote2/images/cut.png
/usr/share/nixnote2/images/datetime.png
/usr/share/nixnote2/images/delete.png
/usr/share/nixnote2/images/down_arrow_small.png
/usr/share/nixnote2/images/emailIcon.png
/usr/share/nixnote2/images/encrypt.png
/usr/share/nixnote2/images/eraser.png
/usr/share/nixnote2/images/expanded.png
/usr/share/nixnote2/images/favorites.png
/usr/share/nixnote2/images/fileclose.png
/usr/share/nixnote2/images/fontColor.png
/usr/share/nixnote2/images/fontHilight.png
/usr/share/nixnote2/images/gps.png
/usr/share/nixnote2/images/grid.png
/usr/share/nixnote2/images/hline.png
/usr/share/nixnote2/images/home.png
/usr/share/nixnote2/images/htmlentities.png
/usr/share/nixnote2/images/indent.png
/usr/share/nixnote2/images/italic.png
/usr/share/nixnote2/images/justifyCenter.png
/usr/share/nixnote2/images/justifyLeft.png
/usr/share/nixnote2/images/justifyRight.png
/usr/share/nixnote2/images/left_arrow.png
/usr/share/nixnote2/images/lens.png
/usr/share/nixnote2/images/link.png
/usr/share/nixnote2/images/linked-notebook.png
/usr/share/nixnote2/images/local-notebook.png
/usr/share/nixnote2/images/navigation.png
/usr/share/nixnote2/images/newNote.png
/usr/share/nixnote2/images/notebook-conflict.png
/usr/share/nixnote2/images/notebookSmall.png
/usr/share/nixnote2/images/notebook_old.png
/usr/share/nixnote2/images/numberList.png
/usr/share/nixnote2/images/outdent.png
/usr/share/nixnote2/images/password.png
/usr/share/nixnote2/images/paste.png
/usr/share/nixnote2/images/printer.png
/usr/share/nixnote2/images/public-notebook.png
/usr/share/nixnote2/images/purple-theme
/usr/share/nixnote2/images/purple-theme/home.png
/usr/share/nixnote2/images/purple-theme/left_arrow.png
/usr/share/nixnote2/images/purple-theme/notebook.png
/usr/share/nixnote2/images/purple-theme/purpleThemeInfo.html
/usr/share/nixnote2/images/purple-theme/right_arrow.png
/usr/share/nixnote2/images/purple-theme/stack-purple.png
/usr/share/nixnote2/images/purple-theme/synchronize.png
/usr/share/nixnote2/images/purple-theme/windowIcon1.png
/usr/share/nixnote2/images/purple-theme/windowIcon2.png
/usr/share/nixnote2/images/purple-theme/windowIcon3.png
/usr/share/nixnote2/images/purple-theme/windowIcon4.png
/usr/share/nixnote2/images/purple-theme/windowIcon5.png
/usr/share/nixnote2/images/redo.png
/usr/share/nixnote2/images/right_arrow.png
/usr/share/nixnote2/images/screenCapture.png
/usr/share/nixnote2/images/silhouette.png
/usr/share/nixnote2/images/spellCheck.png
/usr/share/nixnote2/images/splash_logo.png
/usr/share/nixnote2/images/stack.png
/usr/share/nixnote2/images/strikethrough.png
/usr/share/nixnote2/images/subscript.png
/usr/share/nixnote2/images/superscript.png
/usr/share/nixnote2/images/synchronize.png
/usr/share/nixnote2/images/tag.png
/usr/share/nixnote2/images/themeInfo.html
/usr/share/nixnote2/images/todo.png
/usr/share/nixnote2/images/trash.png
/usr/share/nixnote2/images/trayicon.png
/usr/share/nixnote2/images/tree-down.png
/usr/share/nixnote2/images/trunk.png
/usr/share/nixnote2/images/underline.png
/usr/share/nixnote2/images/undo.png
/usr/share/nixnote2/images/up_arrow_small.png
/usr/share/nixnote2/images/usage.png
/usr/share/nixnote2/images/webcam.png
/usr/share/nixnote2/images/windowIcon.png
/usr/share/nixnote2/install.txt
/usr/share/nixnote2/java
/usr/share/nixnote2/java/.classpath
/usr/share/nixnote2/java/.project
/usr/share/nixnote2/java/crypto.jar
/usr/share/nixnote2/java/src
/usr/share/nixnote2/java/src/cx
/usr/share/nixnote2/java/src/cx/fbn
/usr/share/nixnote2/java/src/cx/fbn/encrypt
/usr/share/nixnote2/java/src/cx/fbn/encrypt/Base64.java
/usr/share/nixnote2/java/src/cx/fbn/encrypt/Crypto.java
/usr/share/nixnote2/java/src/cx/fbn/encrypt/EnCrypt.java
/usr/share/nixnote2/license.html
/usr/share/nixnote2/qss
/usr/share/nixnote2/qss/editor.css
/usr/share/nixnote2/shortcuts.txt
/usr/share/nixnote2/spell
/usr/share/nixnote2/theme.ini
/usr/share/nixnote2/translations
/usr/share/nixnote2/translations/README
/usr/share/nixnote2/translations/nixnote2_ca.qm
/usr/share/nixnote2/translations/nixnote2_ca.ts
/usr/share/nixnote2/translations/nixnote2_cs_CZ.qm
/usr/share/nixnote2/translations/nixnote2_cs_CZ.ts
/usr/share/nixnote2/translations/nixnote2_da.qm
/usr/share/nixnote2/translations/nixnote2_da.ts
/usr/share/nixnote2/translations/nixnote2_de.qm
/usr/share/nixnote2/translations/nixnote2_de.ts
/usr/share/nixnote2/translations/nixnote2_es.qm
/usr/share/nixnote2/translations/nixnote2_es.ts
/usr/share/nixnote2/translations/nixnote2_fr.qm
/usr/share/nixnote2/translations/nixnote2_fr.ts
/usr/share/nixnote2/translations/nixnote2_ja.qm
/usr/share/nixnote2/translations/nixnote2_ja.ts
/usr/share/nixnote2/translations/nixnote2_pl.qm
/usr/share/nixnote2/translations/nixnote2_pl.ts
/usr/share/nixnote2/translations/nixnote2_pt.qm
/usr/share/nixnote2/translations/nixnote2_pt.ts
/usr/share/nixnote2/translations/nixnote2_ru.qm
/usr/share/nixnote2/translations/nixnote2_ru.ts
/usr/share/nixnote2/translations/nixnote2_sk.qm
/usr/share/nixnote2/translations/nixnote2_sk.ts
/usr/share/nixnote2/translations/nixnote2_zh_CN.qm
/usr/share/nixnote2/translations/nixnote2_zh_CN.ts
/usr/share/nixnote2/translations/nixnote2_zh_TW.qm
/usr/share/nixnote2/translations/nixnote2_zh_TW.ts

# rpm --erase  nixnote2-2.0_beta5-0.x86_64
warning: file /usr/share/nixnote2/translations/nixnote2_zh_TW.ts: remove failed: No such file or directory
warning: file /usr/share/nixnote2/translations/nixnote2_zh_TW.qm: remove failed: No such file or directory
...
warning: file /usr/share/nixnote2/README.txt: remove failed: No such file or directory
warning: file /usr/share/nixnote2: remove failed: No such file or directory
warning: file /usr/share/applications/nixnote2.desktop: remove failed: No such file or directory
warning: file /usr/bin/nixnote2: remove failed: No such file or directory

[Again just to confirm]
# rpm --erase  nixnote2-2.0_beta5-0.x86_64
error: package nixnote2-2.0_beta5-0.x86_64 is not installed
# rpm -iv nixnote2-2.0_beta5-0.x86_64.rpm 
Preparing packages...
nixnote2-2.0_beta5-0.x86_64

Now it will work fine
$ nixnote2
 INFO 2015-11-23 21:01:29.467 ( main.cpp @ 157 ) Built on  Nov 22 2015  at  15:45:23 
 INFO 2015-11-23 21:01:29.468 ( main.cpp @ 158 ) Built with Qt 4.8.7 running on 4.8.6 
...

**Comment by jeffbuhrt** [comment] 2015-11-24 02:19
(apparently '# ' at the start of a line must be markup)

**Comment by baumgarr** [comment] 2015-12-10 22:04
This should be fixed in beta 6 that I just uploaded.  Unfortunately the problem is in the beta 5 RPM, so you'll need to un-install beta 5 before installing beta 6 or you'll have the same problem.

**Closed by baumgarr** 2015-12-10 22:04 UTC
