### ISSUE TITLE
startup error when loading WebCam plugin

### ISSUE THREAD

**Issue by zhtengw** [baumgarr/nixnote2#231] opened 2016-12-06 12:27 UTC
I build nixnote2 and its WebCam plugin with Qt 5.6.2 and opencv 3.1. Startup error occured when loading WebCam plugin: "nixnote2: symbol lookup error: /usr/share/nixnote2/plugins/libwebcamplugin.so: undefined symbol: _ZN2cv12VideoCaptureC1Ei".

And nixnote2 can run without errors when the libwebcamplugin.so deleted.

------ldd /libwebcamplugin.so-------
	linux-vdso.so.1 (0x00007ffc7d3f8000)
	libopencv_core.so.3.1 => /usr/lib64/libopencv_core.so.3.1 (0x00007f6e1ffc4000)
	libopencv_imgproc.so.3.1 => /usr/lib64/libopencv_imgproc.so.3.1 (0x00007f6e1fafd000)
	libQt5Widgets.so.5 => /usr/lib64/libQt5Widgets.so.5 (0x00007f6e1f47f000)
	libQt5Gui.so.5 => /usr/lib64/libQt5Gui.so.5 (0x00007f6e1ef7d000)
	libQt5Core.so.5 => /usr/lib64/libQt5Core.so.5 (0x00007f6e1eaf0000)
	libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6 (0x00007f6e1e6f8000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f6e1e4e1000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f6e1e148000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f6e1df32000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f6e1dd2e000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6e1db12000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f6e1d90a000)
	libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007f6e1d69f000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f6e1d39a000)
	libgomp.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libgomp.so.1 (0x00007f6e1d178000)
	libharfbuzz.so.0 => /usr/lib64/libharfbuzz.so.0 (0x00007f6e1cf0e000)
	libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007f6e1ccd9000)
	libicui18n.so.58 => /usr/lib64/libicui18n.so.58 (0x00007f6e1c85d000)
	libicuuc.so.58 => /usr/lib64/libicuuc.so.58 (0x00007f6e1c4b0000)
	libpcre16.so.0 => /usr/lib64/libpcre16.so.0 (0x00007f6e1c248000)
	libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007f6e1bf2d000)
	libsystemd.so.0 => /usr/lib64/libsystemd.so.0 (0x00007f6e1bc8f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6e205f5000)
	libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007f6e1ba63000)
	libxcb-dri3.so.0 => /usr/lib64/libxcb-dri3.so.0 (0x00007f6e1b860000)
	libxcb-present.so.0 => /usr/lib64/libxcb-present.so.0 (0x00007f6e1b65d000)
	libxcb-sync.so.1 => /usr/lib64/libxcb-sync.so.1 (0x00007f6e1b456000)
	libxshmfence.so.1 => /usr/lib64/libxshmfence.so.1 (0x00007f6e1b253000)
	libglapi.so.0 => /usr/lib64/libglapi.so.0 (0x00007f6e1b024000)
	libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f6e1ae12000)
	libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x00007f6e1ac0f000)
	libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007f6e1aa08000)
	libX11-xcb.so.1 => /usr/lib64/libX11-xcb.so.1 (0x00007f6e1a806000)
	libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f6e1a4bf000)
	libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f6e1a296000)
	libxcb-glx.so.0 => /usr/lib64/libxcb-glx.so.0 (0x00007f6e1a07a000)
	libxcb-dri2.so.0 => /usr/lib64/libxcb-dri2.so.0 (0x00007f6e19e75000)
	libXxf86vm.so.1 => /usr/lib64/libXxf86vm.so.1 (0x00007f6e19c6f000)
	libdrm.so.2 => /usr/lib64/libdrm.so.2 (0x00007f6e19a60000)
	libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007f6e197b4000)
	libgraphite2.so.3 => /usr/lib64/libgraphite2.so.3 (0x00007f6e19585000)
	libicudata.so.58 => /usr/lib64/libicudata.so.58 (0x00007f6e17a84000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f6e17811000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007f6e1760b000)
	liblz4.so.1 => /usr/lib64/liblz4.so.1 (0x00007f6e173f8000)
	libgcrypt.so.20 => /usr/lib64/libgcrypt.so.20 (0x00007f6e170ea000)
	libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f6e16ee6000)
	libXdmcp.so.6 => /usr/lib64/libXdmcp.so.6 (0x00007f6e16ce0000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f6e16acf000)
	libgpg-error.so.0 => /usr/lib64/libgpg-error.so.0 (0x00007f6e168bb000)
	libbsd.so.0 => /usr/lib64/libbsd.so.0 (0x00007f6e166a5000)

**Comment by baumgarr** [comment] 2016-12-06 23:47
I can't recreate this. About the only thing I can think is that it has something to do with a newer version of OpenCV or Qt 5.6 when compared to Qt5.5. I made a change so it should compile against Qt4 again, so you could try that to see if it alters the behavior.

Deleting it corrects the problem because it won't try to load the plugin. Everything should work fine but you won't be able to create a webcam note. The same with the hunspell plugin. It isn't required but you cannot issue a spell check without it.

**Comment by baumgarr** [comment] 2016-12-07 00:00
This looks like a duplicate of https://github.com/baumgarr/nixnote2/issues/220.

**Closed** 2016-12-07 00:00 UTC

**Comment by zhtengw** [comment] 2016-12-07 03:33
Hi, baumgarr. I don't think it is a same issue with the hunspell plugin. I just downgraded the opencv to version 2.4, and recompiled nixnote2. Then the nixnote starts without errors and WebCam notes worked. So, this issue is just about the version of opencv.
