### ISSUE TITLE
NN2 Beta5 loops (100% processor) on some notes

### ISSUE THREAD

**Issue by jeffbuhrt** [baumgarr/nixnote2#102] opened 2015-11-25 04:17 UTC
It seems a picture 
The fast polling on descriptor 13 (/tmp/.X11-unix/X0) is what is causing nixnote2 to use 100% cpu. If you switch to a text note the fast polling stops.

One note that loops:
<div><img type="image/jpeg" hash="f9120f3801ee8fae1f6718054101b711" src="file:///home/jbuhrt/.nixnote/tmp-1/3053.png" oncontextmenu="window.browserWindow.imageContextMenu('3053', '3053.jpg');" onload="this.src='file:///home/jbuhrt/.nixnote/tmp-1/3053.png';" en-tag="en-media" lid="3053"></div><div></div>

I tried exporting a note and importing into an empty nixnote, but it didn't repeat the problem.

I am not sure if it is related but switching away can lock up NN2_b5, giving:
(nixnote2:3822): GLib-GObject-CRITICAL **: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
(nixnote2:3822): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
[The reason I think it might be related is until I kill nixnote, I might not be able to copy the text from the text window.]

This is on Fedora 23, 64bit: Kernel 4.2.6-300.fc23.x86_64

To repeat: 
1) Turn off sync on startup to reduce the extra noise in the output for #2, then exit
2) strace -f nixnote2 > nn.out 2>&1
3) Select a test note, wait a few, exit

[pid 30191] close(13)                   = 0
[pid 30191] socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC, 0) = 13
[pid 30191] connect(13, {sa_family=AF_LOCAL, sun_path=@"/tmp/.X11-unix/X0"}, 20) = 0
[pid 30191] getpeername(13, {sa_family=AF_LOCAL, sun_path=@"/tmp/.X11-unix/X0"}, [20]) = 0
...
[pid 30191] getsockname(13, {sa_family=AF_LOCAL, NULL}, [2]) = 0
[pid 30191] fcntl(13, F_GETFL)          = 0x2 (flags O_RDWR)
[pid 30191] fcntl(13, F_SETFL, O_RDWR|O_NONBLOCK) = 0
[pid 30191] fcntl(13, F_SETFD, FD_CLOEXEC) = 0
[pid 30191] poll([{fd=13, events=POLLIN|POLLOUT}], 1, 4294967295) = 1 ([{fd=13, revents=POLLOUT}])
[pid 30191] writev(13, [{"l\0\v\0\0\0\22\0\20\0\0\0", 12}, {"", 0}, {"MIT-MAGIC-COOKIE-1", 18}, {"\0\0", 2}, {"\337\313\35\274\232^\22\352\312\356\215@\351pX\261", 16}, {"", 0}], 6) = 48
[pid 30191] recvfrom(13, 0x55df77548630, 8, 0, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 30191] poll([{fd=13, events=POLLIN}], 1, 4294967295) = 1 ([{fd=13, revents=POLLIN}])
[pid 30191] recvfrom(13, "\1\0\v\0\0\0\362\0", 8, 0, NULL, NULL) = 8
[pid 30191] recvfrom(13, "\300\r\264\0\0\0\0\2\377\377\37\0\0\1\0\0\16\0\377\377\1\7\0\0  \10\377\0\0\0\0"..., 968, 0, NULL, NULL) = 968
[pid 30191] poll([{fd=13, events=POLLIN|POLLOUT}], 1, 4294967295) = 1 ([{fd=13, revents=POLLOUT}])
[pid 30191] writev(13, [{"b\0\5\0\f\0\0\0BIG-REQUESTS", 20}], 1) = 20
[pid 30191] poll([{fd=13, events=POLLIN}], 1, 4294967295) = 1 ([{fd=13, revents=POLLIN}])
[pid 30191] recvmsg(13, {msg_name(0)=NULL, msg_iov(1)=[{"\1\0\1\0\0\0\0\0\1\205\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
[pid 30191] poll([{fd=13, events=POLLIN|POLLOUT}], 1, 4294967295) = 1 ([{fd=13, revents=POLLOUT}])
[pid 30191] writev(13, [{"\205\0\1\0", 4}], 1) = 4
[pid 30191] poll([{fd=13, events=POLLIN}], 1, 4294967295) = 1 ([{fd=13, revents=POLLIN}])
[pid 30191] writev(13, [{"\205\0\1\0", 4}], 1) = 4
[pid 30191] poll([{fd=13, events=POLLIN}], 1, 4294967295) = 1 ([{fd=13, revents=POLLIN}])
[pid 30191] recvmsg(13, {msg_name(0)=NULL, msg_iov(1)=[{"\1\0\2\0\0\0\0\0\377\377?\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
[pid 30191] recvmsg(13, 0x7ffef41c07d0, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 30191] poll([{fd=13, events=POLLIN|POLLOUT}], 1, 4294967295) = 1 ([{fd=13, revents=POLLOUT}])
[pid 30191] writev(13, [{"7\0\5\0\0\0\0\2\300\0\0\0\10\0\0\0\377\377\377\0\24\0\6\0\300\0\0\0\27\0\0\0"..., 44}, {NULL, 0}, {"", 0}], 3) = 44
[pid 30191] poll([{fd=13, events=POLLIN}], 1, 4294967295) = 1 ([{fd=13, revents=POLLIN}])
[pid 30191] recvmsg(13, {msg_name(0)=NULL, msg_iov(1)=[{"\1\10\4\0 \0\0\0\37\0\0\0\0\0\0\0}\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 160
[pid 30191] recvmsg(13, 0x7ffef41c0810, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 30191] poll([{fd=13, events=POLLIN|POLLOUT}], 1, 4294967295) = 1 ([{fd=13, revents=POLLOUT}])
[pid 30191] writev(13, [{"b\0\5\0\t\0\0\2", 8}, {"XKEYBOARD", 9}, {"\0\0\0", 3}], 3) = 20
[pid 30191] poll([{fd=13, events=POLLIN}], 1, 4294967295) = 1 ([{fd=13, revents=POLLIN}])
[pid 30191] recvmsg(13, {msg_name(0)=NULL, msg_iov(1)=[{"\1\0\5\0\0\0\0\0\1\207U\211\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
[pid 30191] recvmsg(13, 0x7ffef41c06e0, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 30191] recvmsg(13, 0x7ffef41c06e0, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 30191] poll([{fd=13, events=POLLIN|POLLOUT}], 1, 4294967295) = 1 ([{fd=13, revents=POLLOUT}])
[pid 30191] writev(13, [{"\207\0\2\0\1\0\0\0", 8}, {NULL, 0}, {"", 0}], 3) = 8
...
[pid 30191] poll([{fd=13, events=POLLIN}], 1, 4294967295) = 1 ([{fd=13, revents=POLLIN}])
[pid 30191] recvmsg(13, {msg_name(0)=NULL, msg_iov(1)=[{"\1\0\22\0\0\0\0\0#\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 512
[pid 30191] recvmsg(13, {msg_name(0)=NULL, msg_iov(1)=[{"\1\0\"\0\0\0\0\0y\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0
\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 800
[pid 30191] recvmsg(13, {msg_name(0)=NULL, msg_iov(1)=[{"\1\0;\0\0\0\0\0\313\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0
\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 768
[pid 30191] recvmsg(13, {msg_name(0)=NULL, msg_iov(1)=[{"\1\0S\0\0\0\0\0\253\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 800
[pid 30191] recvmsg(13, {msg_name(0)=NULL, msg_iov(1)=[{"\1\0l\0\0\0\0\0\321\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 704
[pid 30191] recvmsg(13, 0x7ffef41c0830, 0) = -1 EAGAIN (Resource temporarily unavailable)
...

**Comment by baumgarr** [comment] 2015-11-27 21:32
I can't reproduce any looping.  Is it a picture only note or does it have other text mixed in? What window manager are you using? 

If you change the message level to trace under Preferences/Debug it will give a better indication of what is happening within NixNote.

**Comment by jeffbuhrt** [comment] 2015-11-29 03:16
I see the ~100% processor when displaying messages with a picture. Some have text and some not.
I am using Gnome. The looping and using ~100% processor I am pretty sure is not directly application level, but might be inside an X library. Whenever I select a text only note NN uses very little CPU.

So viewing random message 1, this is static, nothing scrolling up the screen, this is an image and a subject, no text:
...
DEBUG 2015-11-28 22:10:50.034 ( threads/indexrunner.cpp @ 62 ) Starting IndexRunner 
DEBUG 2015-11-28 22:10:50.034 ( sql/databaseconnection.cpp @ 37 ) SQL drivers available:  ("QSQLITE") 
TRACE 2015-11-28 22:10:50.034 ( sql/databaseconnection.cpp @ 38 ) Adding database SQLITE 
TRACE 2015-11-28 22:10:50.034 ( sql/databaseconnection.cpp @ 40 ) Setting DB name 
TRACE 2015-11-28 22:10:50.034 ( sql/databaseconnection.cpp @ 42 ) Opening database 
TRACE 2015-11-28 22:10:50.034 ( sql/databaseconnection.cpp @ 50 ) Preparing tables 
TRACE 2015-11-28 22:10:50.035 ( sql/databaseconnection.cpp @ 79 ) Creating filter table 
TRACE 2015-11-28 22:10:50.037 ( sql/databaseconnection.cpp @ 82 ) Adding to filter table 
TRACE 2015-11-28 22:10:50.040 ( sql/databaseconnection.cpp @ 84 ) Addition complete 
DEBUG 2015-11-28 22:10:50.040 ( threads/indexrunner.cpp @ 70 ) Indexrunner initialized. 
TRACE 2015-11-28 22:10:50.041 ( gui/browserWidgets/tageditornewtag.cpp @ 215 ) Entering event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:50.041 ( gui/browserWidgets/tageditornewtag.cpp @ 228 ) Exiting event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:50.041 ( gui/browserWidgets/tageditornewtag.cpp @ 215 ) Entering event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:50.041 ( gui/browserWidgets/tageditornewtag.cpp @ 228 ) Exiting event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:50.041 ( gui/browserWidgets/tageditornewtag.cpp @ 215 ) Entering event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:50.041 ( gui/browserWidgets/tageditornewtag.cpp @ 228 ) Exiting event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:50.438 ( gui/browserWidgets/tageditornewtag.cpp @ 215 ) Entering event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:50.438 ( gui/browserWidgets/tageditornewtag.cpp @ 228 ) Exiting event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:50.452 ( gui/browserWidgets/tageditornewtag.cpp @ 215 ) Entering event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:50.452 ( gui/browserWidgets/tageditornewtag.cpp @ 228 ) Exiting event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:50.465 ( gui/browserWidgets/tageditornewtag.cpp @ 215 ) Entering event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:50.465 ( gui/browserWidgets/tageditornewtag.cpp @ 228 ) Exiting event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:50.869 ( gui/browserWidgets/tageditornewtag.cpp @ 215 ) Entering event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:50.869 ( gui/browserWidgets/tageditornewtag.cpp @ 228 ) Exiting event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:52.837 ( gui/browserWidgets/tageditornewtag.cpp @ 215 ) Entering event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:52.837 ( gui/browserWidgets/tageditornewtag.cpp @ 228 ) Exiting event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:52.843 ( gui/browserWidgets/tageditornewtag.cpp @ 215 ) Entering event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:52.843 ( gui/browserWidgets/tageditornewtag.cpp @ 228 ) Exiting event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:52.854 ( gui/browserWidgets/tageditornewtag.cpp @ 215 ) Entering event : 15TagEditorNewTag 
TRACE 2015-11-28 22:10:52.855 ( gui/browserWidgets/tageditornewtag.cpp @ 228 ) Exiting event : 15TagEditorNewTag 

This is a note with text and an image:
...
TRACE 2015-11-28 22:14:47.834 ( gui/browserWidgets/tageditor.cpp @ 343 ) Exiting setAccount : 9TagEditor 
DEBUG 2015-11-28 22:14:47.834 ( gui/nbrowserwindow.cpp @ 519 ) Setting notebook 
DEBUG 2015-11-28 22:14:47.834 ( gui/nbrowserwindow.cpp @ 522 ) Setting URL 
DEBUG 2015-11-28 22:14:47.834 ( gui/nbrowserwindow.cpp @ 525 ) Setting note attributes 
DEBUG 2015-11-28 22:14:47.834 ( gui/nbrowserwindow.cpp @ 529 ) Setting sourceUrl 
DEBUG 2015-11-28 22:14:47.835 ( gui/nbrowserwindow.cpp @ 534 ) Calling set source 
DEBUG 2015-11-28 22:14:47.878 ( gui/nbrowserwindow.cpp @ 544 ) Checking thumbanail 
DEBUG 2015-11-28 22:14:47.878 ( gui/nbrowserwindow.cpp @ 552 ) Exiting setContent 
TRACE 2015-11-28 22:14:47.878 ( sql/notetable.cpp @ 870 ) Fetching Resources?  false  With binary?  false 
TRACE 2015-11-28 22:14:47.880 ( sql/notetable.cpp @ 875 ) Fetched resources 
DEBUG 2015-11-28 22:14:47.880 ( sql/notebooktable.cpp @ 931 ) Linked Notebook Found:  true 
DEBUG 2015-11-28 22:14:47.880 ( sql/notebooktable.cpp @ 932 ) Linked Notebook URI set:  false 
TRACE 2015-11-28 22:14:48.885 ( gui/browserWidgets/tageditornewtag.cpp @ 215 ) Entering event : 15TagEditorNewTag 
TRACE 2015-11-28 22:14:48.885 ( gui/browserWidgets/tageditornewtag.cpp @ 228 ) Exiting event : 15TagEditorNewTag 
TRACE 2015-11-28 22:14:48.905 ( gui/browserWidgets/tageditornewtag.cpp @ 215 ) Entering event : 15TagEditorNewTag 
TRACE 2015-11-28 22:14:48.906 ( gui/browserWidgets/tageditornewtag.cpp @ 228 ) Exiting event : 15TagEditorNewTag 
TRACE 2015-11-28 22:14:51.133 ( gui/browserWidgets/tageditornewtag.cpp @ 215 ) Entering event : 15TagEditorNewTag 
TRACE 2015-11-28 22:14:51.133 ( gui/browserWidgets/tageditornewtag.cpp @ 228 ) Exiting event : 15TagEditorNewTag 
TRACE 2015-11-28 22:14:51.137 ( gui/browserWidgets/tageditornewtag.cpp @ 215 ) Entering event : 15TagEditorNewTag 
TRACE 2015-11-28 22:14:51.137 ( gui/browserWidgets/tageditornewtag.cpp @ 228 ) Exiting event : 15TagEditorNewTag 
TRACE 2015-11-28 22:14:51.148 ( gui/browserWidgets/tageditornewtag.cpp @ 215 ) Entering event : 15TagEditorNewTag 
TRACE 2015-11-28 22:14:51.148 ( gui/browserWidgets/tageditornewtag.cpp @ 228 ) Exiting event : 15TagEditorNewTag 


When NN2_beta5 locks upstops responding I get a Force Quit/Wait and see:
...
TRACE 2015-11-28 22:08:11.387 ( html/noteformatter.cpp @ 177 ) Entering preHtmlFormat : 
TRACE 2015-11-28 22:08:11.387 ( html/noteformatter.cpp @ 196 ) Exiting preHtmlFormat : 
TRACE 2015-11-28 22:08:11.387 ( html/noteformatter.cpp @ 136 ) About to set content 
TRACE 2015-11-28 22:08:11.388 ( html/noteformatter.cpp @ 140 ) Starting to modify tags 
TRACE 2015-11-28 22:08:11.388 ( html/noteformatter.cpp @ 209 ) Entering modifyTags : 
TRACE 2015-11-28 22:08:11.388 ( html/noteformatter.cpp @ 213 ) Searching for all en-media tags; 
TRACE 2015-11-28 22:08:11.388 ( html/noteformatter.cpp @ 215 ) Search complete:  1 
TRACE 2015-11-28 22:08:11.388 ( html/noteformatter.cpp @ 223 ) En-Media tag type:  "application" 
TRACE 2015-11-28 22:08:11.388 ( html/noteformatter.cpp @ 476 ) Entering modifyApplicationTags : 
TRACE 2015-11-28 22:08:11.422 ( html/noteformatter.cpp @ 710 ) Entering modifyPdfTags : 

(nixnote2:28662): GLib-GObject-CRITICAL **: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed

(nixnote2:28662): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

**Comment by jeffbuhrt** [comment] 2015-12-04 14:24
I shared a test folder for #112 to baumgarr and a new account I created.

I created a test Evernote account, moved .nixnote to .nixnote-old, and shared the test folder to the new account. I then repeated this problem (#102) and #112 under Fedora 23 64bit gnome.
-Again this would be a totally fresh user of both NixNote2 beta 5 and Evernote, no prior configs, etc.

The trick to start +/-100% use is search for 'bulb'. If you have the wattage vs lumin test note open or select it, the NixNote cpu utilization will go to ~100% when it is open.  Once you see the yellow highligher markings note nixnote is using 100% cpu, but goes to ~1% when you switch away

The problem is something that has called a X/gnome lib call and is using a stale/bad handle to the X server. That is the large number of repeating calls on descriptor 13 in my test case above:
...
[pid  9871] recvmsg(15, 0x7fffbe4286d0, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid  9871] poll([{fd=10, events=POLLIN}, {fd=13, events=POLLIN}, {fd=14, events=POLLIN}, {fd=15, events=POLLIN}, {fd=16, events=POLLIN}, {fd=26, 
events=POLLIN}, {fd=37, events=POLLIN}], 7, 0) = 1 ([{fd=10, revents=POLLIN}])
[pid  9871] read(10, "\3\0\0\0\0\0\0\0", 16) = 8
[pid  9871] recvmsg(13, 0x7fffbe428700, 0) = -1 EAGAIN (Resource temporarily unavailable)
...

Note this repeats with the new clean testcase user.

**Comment by baumgarr** [comment] 2015-12-04 18:50
I think I have it fixed in the latest source on GitHub.  If not, I also added an option to disable image highlighting for searches.  Disabling it also speeds things up a bit because it doesn't need to do as much searching & writing to disk.

Thanks.

**Closed by baumgarr** 2015-12-04 18:50 UTC
