### ISSUE TITLE
Theme preferences not saved in material design

### ISSUE THREAD

**Issue by adamoxford** [baumgarr/nixnote2#312] opened 2017-03-21 06:57 UTC
Minor issue, but on my Ubuntu 16.10 using the Material theme, Nixnote doesn't save layout preferences after restart (ie. wide or narrow note list, custom columns in note list). Works fine with system default theme. All settings in Edit>Preferences seem to save OK.

**Comment by baumgarr** [comment] 2017-03-21 11:28
I can't recreate this on my Kubuntu or Windows machine. There shouldn't be any real interaction between the two that I can think of.

Are you shutting NixNote down cleanly?
I'm assuming you are using 2.0, or did you build it from the source or use the PPA? 
Are you using Qt4 or Qt5?
Are you using Unity & do you have another window manager you can test?

**Comment by Niel0** [comment] 2017-04-07 16:57
I'm using Nixnote2 stable on 64bit Linux Mint Cinnamon 18.1 and had been scratching my head for days after Nixnote repeatedly failed to save layout preferences after a restart - most annoyingly, custom columns in the note list. After reading the comment by adamoxford I changed from the Material theme to the default theme and, bingo!, column preferences were saved after reboots. By column preferences, I mean the display of information such as "Has To-do", "Has encryption", "Reminder due", "Reminder completed".

**Comment by adamoxford** [comment] 2017-04-07 17:41
Sorry @baumgarr I missed the reply. It's v2.0 in Unity, Qt5. Was installed from the Sourceforge deb (https://sourceforge.net/projects/nevernote/files/NixNote2%20-%202.0/Linux/Qt5/) - which was obviously my mistake... I have it running on another machine (don't have any other DEs installed) installed from the PPA and Material theme is not an option.

**Comment by baumgarr** [comment] 2017-04-11 00:42
I think we're mixing issues here.

The theme won't have anything to do with what is saved as far as what preferences are saved. My guess is that it is being minimized to the tray or not being shut down properly when you logoff. 

The problem is that it only saves these things when the program is stopped cleanly. If you have it minimized to tray or you just do a logoff or shutdown  then Linux sends a sighup to the program and it doesn't have time to save it properly.

If that is the case, it is fixed in 2.0.1.

**Comment by Niel0** [comment] 2017-04-11 08:50
OK @baumgarr, I am not arguing the point, all I can say is that after reading the comment by @adamoxford I changed theme and my problem was gone. I conceded that the outcome may have been achieved by my having cleanly shut down nixnote2 and checked again via via "killall" before restarting it to find layout changes had been saved. I can't seem to find 2.0.1 anywhere yet, is it available?

**Comment by baumgarr** [comment] 2017-08-12 17:36
This should be fixed in the next release.

**Closed by baumgarr** 2017-08-12 17:36 UTC
