### ISSUE TITLE
malloc error when trying to use signalGui 

### ISSUE THREAD

**Issue by ndroftheline** [baumgarr/nixnote2#255] opened 2017-01-20 22:46 UTC
Hey, 

Loving NixNote2 so far. I'm on 2.0-Beta11, running on a modified Ubuntu 16.04 LTS distribution called GalliumOS, which is for Chromebook devices. In case it matters I'm on the Dell Chromebook 13. 

I'm trying to configure a global shortcut to add a new Note. I know how to do this with my desktop environment, but the commands to manipulate the Gui (aside from simply showing it) aren't working that I can tell.

When I issue the command,  `nixnote2 signalGui --newNote` or `nixnote2 signalGui --newExternalNote` the process appears to simply hang until I ctrl+c it. 

When using the command, `nixnote2 signalGui --show` I get an immediate abort and a traceback: https://pastebin.ubuntu.com/23835995/ 

I'm currently working around it by tying a keyboard shortcut to `nixnote2 show_window`, which unfortunately fullscreens nixnote2, but at least I can then use the additional shortcut Ctrl+N to start a new note, which is ultimately my goal. 

Any known way to resolve this? Please let me know if I can be of further help. 

Thanks,

~Micah

**Comment by baumgarr** [comment] 2017-01-21 01:57
I have an idea of what it might be, but I can't recreate the original problem so it is difficult to say if I am correct in my assumption.

Did you get NixNote from SourceForge or from somewhere else?

**Comment by baumgarr** [comment] 2017-01-21 02:22
Before I give the wrong impression, I think the problem is that there is an uninitialized pointer that is causing it to crash. I want to know where you got it from because it will let me know how best to give you a potential fix.

Thanks!

**Comment by ndroftheline** [comment] 2017-01-21 02:43
I got the package from Sourceforge. This is the download address from my
download history:
https://pilotfiber.dl.sourceforge.net/project/nevernote/NixNote2%20-%20Beta%2011/Linux/Qt4/nixnote2-2.0-beta11_amd64.deb

~Micah

**Comment by baumgarr** [comment] 2017-01-21 23:00
I think I have it fixed. You can either wait until the next release or, if you don't want to wait, you can send me your email & I'll email you a new binary. Your choice.

**Comment by ndroftheline** [comment] 2017-01-22 17:15
Wow awesome thanks. I'll take the binary. micah.b.roth@gmail.com . Will it be a .deb package I simply install or will I need to swap files out manually? Happy to do either, but some guidance would be useful. Also - anything I can do to thank you?

**Comment by baumgarr** [comment] 2017-01-22 17:44
It should be on its way. Let me know if you don't get it. I also removed your email address from the post above.

Thanks.

**Comment by ndroftheline** [comment] 2017-01-22 19:52
Thanks, I did a little googling and didn't find an easy way to DM you via
github. What is best practice in this situation?

**Comment by baumgarr** [comment] 2017-01-31 02:46
Spoke offline & fix has been verified. Closing.

**Closed by baumgarr** 2017-01-31 02:46 UTC
Labels: bug
