### ISSUE TITLE
Feature request - button to insert formatted code block

### ISSUE THREAD

**Issue by jessalyn298** [baumgarr/nixnote2#355] opened 2017-07-27 10:11 UTC
Moved to Linux and needed a nice replacement for Evernote - Nixnote is a cracking replacement. 

Only one thing missing - Evernote has a nice button {} that allows insertion of text formatted in a grey box with a font different to the body for lines of code to be written in. 

I can't find a way to do this nicely on Nixnote - save putting it into a one cell table. 

Thanks in advance :)

**Comment by baumgarr** [comment] 2017-07-27 10:16
It would be helpful if you could export a sample since I don't have easy access to my Windows version of Evernote. Could you export a simple note and attach it to this request?  Thanks.

**Comment by jessalyn298** [comment] 2017-07-27 10:45
![screenshot from 2017-07-27 11-43-11](https://user-images.githubusercontent.com/30495397/28666835-e957a84a-72c0-11e7-90c0-b296f71ca755.png)

So weirdly, this button is not available on the online Evernote client in Firefox, but is available on Chrome - the {} button. 

I hope this helps

**Comment by baumgarr** [comment] 2017-07-27 10:49
If you could synchronize that with NixNote, then export it as a nnex file and attach it to this, that would be helpful.

**Comment by jessalyn298** [comment] 2017-07-27 11:38
Couldn't add nnex file to this thread- sorry - I pasted below instead - hope that's ok!


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NixNote-Export>
<nixnote-export version="2" exportType="export" application="NixNote" applicationVersion="2.x">
    <Note>
        <Guid>e9231fbe-6b5a-4650-b0bc-2becf99b59e2</Guid>
        <Title>Note sample</Title>
        <Content><![CDATA[<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note><div><br clear="none" /></div><div><div>This is a command I used on Linux:<br clear="none" /></div><div style="color: #333333; font-family: 'Helvetica Neue', Helvetica, 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial;"><div style="background: #eeffcc;"><pre style="font-family: Monaco, Menlo, Consolas, 'Courier New', monospace; font-size: 0.9em; border-radius: 4px; letter-spacing: 0.015em; padding: 1em; border: 1px solid #cccccc; background-color: #f8f8f8; overflow-x: auto;">$ This is a command
</pre></div></div>This is a second command I used on Linux:<br clear="none" /></div><div><pre style="font-family: Monaco, Menlo, Consolas, 'Courier New', monospace; font-size: 0.9em; border-radius: 4px; letter-spacing: 0.015em; padding: 1em; border: 1px solid #cccccc; background-color: #f8f8f8; overflow-x: auto;">$ sudo second command</pre></div><div><br /></div><div><br clear="none" /></div></en-note>]]></Content>
        <ContentHash>0d3fd4ee845c4f8328ed4bcea4caec5c</ContentHash>
        <ContentLength>1383</ContentLength>
        <Created>1501151441000</Created>
        <Updated>1501152320000</Updated>
        <Active>true</Active>
        <UpdateSequenceNumber>5327</UpdateSequenceNumber>
        <NotebookGuid>f2fd3322-e496-4d32-a174-a59b58645f56</NotebookGuid>
        <Attributes>
            <Author>Jess Friedersdorff</Author>
        </Attributes>
        <Dirty>false</Dirty>
    </Note>
</nixnote-export>

**Comment by jessalyn298** [comment] 2017-07-27 11:39
It wouldn't let me add .nnex file - sorry, so just pasted here. Hope that's ok :)


`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NixNote-Export>
<nixnote-export version="2" exportType="export" application="NixNote" applicationVersion="2.x">
    <Note>
        <Guid>e9231fbe-6b5a-4650-b0bc-2becf99b59e2</Guid>
        <Title>Note sample</Title>
        <Content><![CDATA[<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note><div><br clear="none" /></div><div><div>This is a command I used on Linux:<br clear="none" /></div><div style="color: #333333; font-family: 'Helvetica Neue', Helvetica, 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial;"><div style="background: #eeffcc;"><pre style="font-family: Monaco, Menlo, Consolas, 'Courier New', monospace; font-size: 0.9em; border-radius: 4px; letter-spacing: 0.015em; padding: 1em; border: 1px solid #cccccc; background-color: #f8f8f8; overflow-x: auto;">$ This is a command
</pre></div></div>This is a second command I used on Linux:<br clear="none" /></div><div><pre style="font-family: Monaco, Menlo, Consolas, 'Courier New', monospace; font-size: 0.9em; border-radius: 4px; letter-spacing: 0.015em; padding: 1em; border: 1px solid #cccccc; background-color: #f8f8f8; overflow-x: auto;">$ sudo second command</pre></div><div><br /></div><div><br clear="none" /></div></en-note>]]></Content>
        <ContentHash>0d3fd4ee845c4f8328ed4bcea4caec5c</ContentHash>
        <ContentLength>1383</ContentLength>
        <Created>1501151441000</Created>
        <Updated>1501152320000</Updated>
        <Active>true</Active>
        <UpdateSequenceNumber>5327</UpdateSequenceNumber>
        <NotebookGuid>f2fd3322-e496-4d32-a174-a59b58645f56</NotebookGuid>
        <Attributes>
            <Author>Jess Friedersdorff</Author>
        </Attributes>
        <Dirty>false</Dirty>
    </Note>
</nixnote-export>`

**Comment by jessalyn298** [comment] 2017-07-27 11:40
'''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NixNote-Export>
<nixnote-export version="2" exportType="export" application="NixNote" applicationVersion="2.x">
    <Note>
        <Guid>e9231fbe-6b5a-4650-b0bc-2becf99b59e2</Guid>
        <Title>Note sample</Title>
        <Content><![CDATA[<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note><div><br clear="none" /></div><div><div>This is a command I used on Linux:<br clear="none" /></div><div style="color: #333333; font-family: 'Helvetica Neue', Helvetica, 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial;"><div style="background: #eeffcc;"><pre style="font-family: Monaco, Menlo, Consolas, 'Courier New', monospace; font-size: 0.9em; border-radius: 4px; letter-spacing: 0.015em; padding: 1em; border: 1px solid #cccccc; background-color: #f8f8f8; overflow-x: auto;">$ This is a command
</pre></div></div>This is a second command I used on Linux:<br clear="none" /></div><div><pre style="font-family: Monaco, Menlo, Consolas, 'Courier New', monospace; font-size: 0.9em; border-radius: 4px; letter-spacing: 0.015em; padding: 1em; border: 1px solid #cccccc; background-color: #f8f8f8; overflow-x: auto;">$ sudo second command</pre></div><div><br /></div><div><br clear="none" /></div></en-note>]]></Content>
        <ContentHash>0d3fd4ee845c4f8328ed4bcea4caec5c</ContentHash>
        <ContentLength>1383</ContentLength>
        <Created>1501151441000</Created>
        <Updated>1501152320000</Updated>
        <Active>true</Active>
        <UpdateSequenceNumber>5327</UpdateSequenceNumber>
        <NotebookGuid>f2fd3322-e496-4d32-a174-a59b58645f56</NotebookGuid>
        <Attributes>
            <Author>Jess Friedersdorff</Author>
        </Attributes>
        <Dirty>false</Dirty>
    </Note>
</nixnote-export>'''

**Comment by jessalyn298** [comment] 2017-07-27 11:41
#<?xml version="1.0" encoding="UTF-8"?>
#<!DOCTYPE NixNote-Export>
#<nixnote-export version="2" exportType="export" application="NixNote" applicationVersion="2.x">
    <Note>
        <Guid>e9231fbe-6b5a-4650-b0bc-2becf99b59e2</Guid>
        <Title>Note sample</Title>
        #<Content><![CDATA[<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note><div><br clear="none" /></div><div><div>This is a command I used on Linux:<br clear="none" /></div><div style="color: #333333; font-family: 'Helvetica Neue', Helvetica, 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial;"><div style="background: #eeffcc;"><pre style="font-family: Monaco, Menlo, Consolas, 'Courier New', monospace; font-size: 0.9em; border-radius: 4px; letter-spacing: 0.015em; padding: 1em; border: 1px solid #cccccc; background-color: #f8f8f8; overflow-x: auto;">$ This is a command
#</pre></div></div>This is a second command I used on Linux:<br clear="none" /></div><div><pre style="font-family: Monaco, Menlo, Consolas, 'Courier New', monospace; font-size: 0.9em; border-radius: 4px; letter-spacing: 0.015em; padding: 1em; border: 1px solid #cccccc; background-color: #f8f8f8; overflow-x: auto;">$ sudo second command</pre></div><div><br /></div><div><br clear="none" /></div></en-note>]]></Content>
        <ContentHash>0d3fd4ee845c4f8328ed4bcea4caec5c</ContentHash>
        <ContentLength>1383</ContentLength>
        <Created>1501151441000</Created>
        <Updated>1501152320000</Updated>
        <Active>true</Active>
        <UpdateSequenceNumber>5327</UpdateSequenceNumber>
        <NotebookGuid>f2fd3322-e496-4d32-a174-a59b58645f56</NotebookGuid>
        <Attributes>
            <Author>Jess Friedersdorff</Author>
        </Attributes>
        <Dirty>false</Dirty>
    </Note>
#</nixnote-export>

**Comment by jessalyn298** [comment] 2017-07-27 11:43
[notes.txt](https://github.com/baumgarr/nixnote2/files/1179786/notes.txt)

Sorry couldn't send a .nnex so it's a text file. :)

**Comment by baumgarr** [comment] 2017-07-27 11:45
Perfect. Thanks!

**Comment by danielmaurer** [comment] 2017-07-27 14:36
This issue is a duplicate of #315

**Comment by baumgarr** [comment] 2017-07-28 02:05
The code block will be in the next release. It won't do syntax highlighting, but it will work similar to Evernote's web interface code block. Let me know if it breaks something.

**Closed by baumgarr** 2017-07-28 02:05 UTC

**Comment by sakhan007** [comment] 2021-04-24 18:35
Thanks for implementing a code block but after the code has been inserted in the text.. there is no way of getting out of it and continue with your writing. Some people have suggested in Evernote forums to add few blank lines and then insert code block a little above and then move to the lines already inserted below the code block. 
It does not look good, the `Cntrl enter` or just `Enter` should take us out of the code block.
