### ISSUE TITLE
Arch (x64) nixnote-beta-2.0_beta4-2

### ISSUE THREAD

**Issue by komitaltrade** [baumgarr/nixnote2#99] opened 2015-11-22 18:40 UTC
After last upgrade, it cannot be launched anymore. I uninstalled and deleted home files also, biut same issue. If it help, it is cinnamon DE under Archx64 (but worked till now.

**Comment by baumgarr** [comment] 2015-11-22 21:13
I'm going to need more details.  Launch it from a command line and paste any error messages.

**Comment by baumgarr** [comment] 2015-11-22 21:15
I'm guessing this is a duplicate of https://github.com/baumgarr/nixnote2/issues/62.

I just uploaded beta 5.  See if it corrects the problem.  There are some problems with Arch because it expects a newer version of curl than beta 4 was built with.  I did a distro upgrade to the latest patches so hopefully beta 5 fixes it.

**Comment by baumgarr** [comment] 2015-11-23 01:05
The other issue was solved with this.  See if it corrects your problem too.

There is a "libcurl-compat" package for arch: https://aur.archlinux.org/packages/libcurl-compat/
Install it and then run:
$ LD_PRELOAD=libcurl.so.3 nixnote2

**Comment by komitaltrade** [comment] 2015-11-26 14:26
Sorry, I was busy. Yes, it "solve" the issue, but it cannot be the solution for "production" (are you agree).

**Comment by baumgarr** [comment] 2015-11-27 20:04
It will need to be a solution until other distros move to newer curl versions.  If I build on a newer version I'll break everyone else.

**Closed by baumgarr** 2015-11-27 20:04 UTC
