### ISSUE TITLE
Notes truncating and disappearing

### ISSUE THREAD

**Issue by jpbrown-15** [baumgarr/nixnote2#304] opened 2017-03-16 21:15 UTC
nixnote2-daily+20170313
Ubuntu 16.10 64-bit

I attempted to make notes out of a couple of website pages from investopedia.com.  Here is one of them.
http://www.investopedia.com/articles/trading/08/darvas.asp

Pasting this page into a new text note accepts the text and pictures, but when navigating to another note, a pop-up appears saying Unable to Save.  "Unable to save this note.  Either tidy isn't installed or the note is too complex to save."

Tidy is installed.

Navigating back to the note, sometimes it actually displays back the full content, other times it truncates it right after the title and by line of Michael Carr.  But once you close and re-open NixNote2, only the heading remains and not the body that previously appeared.

I am able to grab the contents from the web page immediately below the 2 horizontal lines that are under the articles "by line". and save that.  However the initial paste shows the graphics but when navigating away to a different note and then back, the graphics disappear.  No warning or error message.  No contents in the Message Log.

Looking at my other notes clipped from investopedia.com, they have all lost their detail and only include the title and by line followed by the 2 horizontal lines that show on the page.  These losses were all silent drops.

I also reviewed other notes I've clipped from web sites in the past month and they now only have the title and the rest of the notes are gone.

**Comment by baumgarr** [comment] 2017-03-16 22:03
Duplicate of #84

**Comment by jpbrown-15** [comment] 2017-03-16 22:33
This is sad.  The item gets closed citing it as a duplicate of #84 , but the other report is from 1.5 years ago and no indication that it was fixed or not going to be fixed, only that "pasting from a browser may produce something less than good html" and some syncing issues and then closed.  Yet the issue remains.

I don't sync with Evernote and don't use Evernote because of their privacy policy, hence using NN as local only.  Just sad that this issue isn't going to be considered for fix.  It is a horrible user experience when notes disappear silently (and sometimes with a little noise).

**Comment by baumgarr** [comment] 2017-03-16 22:57
It does tell you that it can't save it, so they don't just disappear.

The problem is that Evernote doesn't support HTML, but a strict well-formatted subset. HTML itself can be poorly formatted and pasting it can make it even worse because you may have only part of the web page in the buffer. 

I have to have some way of converting it from HTML to XHTML. Evernote won't even sync with it unless it is well structured XHTML and there are other places in NixNote that would probably break if it wasn't well formatted. Tidy is the best free option I've found to do that, but it isn't always able to do it. When Tidy can't do it then there is nothing I can do. 

The reason it keeps it around until you close it is to give you the option under "View Source" to manually do some type of cleanup. That may give you the ability to save it properly, but once you close it the buffer is lost.

If you don't want to use Evernote's web clipper, I'd say you only have a few options:

1.) Paste it as unformatted text. That will remove all of the HTML & you can format the note yourself.
2.) You may have better luck if you can find some other type of plugin that simplifies the formatting enough so that Tidy can clean it up. It still won't do any image downloading, but it may be enough to keep the formatting.
3.) You can always help by writing some code to fix the problem. :)

Unfortunately with a workaround (Everonote's web clipper) this isn't a high priority. There are 10,000 other things to do. Eventually I may look at it, but I wouldn't guess it will be anytime soon.

Sorry.

**Comment by alkorsan** [comment] 2017-07-23 12:38
There is no way to disable Evernote in Nixnote? so we can then save in html instead of this strict xhtml!

I don t ask for nothing it is just a hope (separate Evernote from this gem called Nixnote),  it is difficult because if someone decide to sync his note with Evernote after being disabled the xhtml option , then he will lose content because Nixnote will have to clean the html, so he will lose content for sure.
and this what our friend did not understand: converting the order into disorder is easy, but auto-convert disorder to order is so hard/impossible.

This is the only notebook software in the world that have all what notebooks should have (unicode bidi ,tabs ,autosave , undo _when opened in tabs_, tables, tree view,html db that was a dream to find it in the 1 million markdown soft that exist in a google search)
 I really was looking for this app from more than 15 years, and I just discovered today after testing 176 app in the last 3 months.

when TexNotesPro died I was alone but now I will never be alone again, I can t believe yet that I found this gem  :)  bye bye zim-wiki you helped me too a lot but you made me crazy with the auto edit of my files and auto link creation.

I really searched some way to donate but I can t find it, I don t know any charity (as I read in the forum), do you have a paypal that I can donate to you directly?

Thank you very very very much for this gem . God bless you

**Comment by baumgarr** [comment] 2017-07-24 00:23
I'm glad you enjoy NixNote. That is a lot of praise. I'm not sure I enjoy it that much. :)

In the advanced (or debug) tab there is an option to disable the strict DTD checking. That will help with removing some of the settings, but overall there isn't a way to disable all XHTML cleanup.  I can look at adding an option to disable all cleanup, but I'm not sure it won't create other problems. 

By disabling strict DTD or (if I build it) the option to bypass cleanup completely you'll never be able to sync with Evernote.

As for the charity, no. I don't have a PayPal account to donate directly. I don't like accepting money because this is a hobby. Taking money for a hobby changes it into a job (and I have enough of those). This way, I can always say "I'm done" and walk away without feeling guilty.  :)

If you are looking for recommendations, I'd donate to the Free Software Foundation (https://my.fsf.org/donate/) or the Red Cross (https://www.redcross.org/donate/donation). 

Thanks,
Randy

**Comment by baumgarr** [comment] 2017-07-24 17:33
The next release will have an option in the Edit/Preferences to disable HTML cleanup. I don't make any guarantee about how well it will work but you're welcome to try it. It won't download any URL images locally. That takes a lot more effort.

**Closed by baumgarr** 2017-07-24 17:33 UTC

**Comment by alkorsan** [comment] 2017-07-24 22:19
I have no words sir to thank you, this is a dream you make real twice now, thank you for all this and thanks to God who made you be in this world in this time in this profession with this heart. God bless you
