### ISSUE TITLE
I Can't search notes with todo

### ISSUE THREAD

**Issue by yoburtu** [baumgarr/nixnote2#106] opened 2015-11-26 08:41 UTC
Hello,

Nixnote 2 version: Beta 5.

When I create a new text note with "todo" check, I can't search this notes with "todo:false" in search section. The column "has to-do" don't have the dot.

If I create the note in web interfaz with "todo", I can search this note and the column "has to-do" has the dot.

Best regards.

**Comment by baumgarr** [comment] 2015-11-27 20:59
I can't reproduce this.  If you create the note in NixNote does the problem remain, or does it happen regardless of where the note is created?

**Comment by yoburtu** [comment] 2015-11-28 23:44
The problem is when I create the note in NixNote. If I create the note in web Client, for example, it work.

Regards.

**Comment by baumgarr** [comment] 2015-12-04 23:44
This should be fixed in the next release.  Thanks!

**Closed by baumgarr** 2015-12-04 23:44 UTC
