### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by quanzhuo** [baumgarr/nixnote2#344] opened 2017-07-01 10:54 UTC
## Distribution
Ubuntu 16.04.2 LTS

## NixNote Verson
2.0

## Description

I create a note titled: "android.os.Build", paste some html formated text to it and then sync. Error occured!

## Details

message log:

> INFO 2017-07-01 18:45:26.786 ( nixnote.cpp @ 1880 ) "Beginning Sync" 
ERROR 2017-07-01 18:45:27.647 ( communication/communicationmanager.cpp @ 557 ) EDAMUserException: 11 
ERROR 2017-07-01 18:45:27.647 ( threads/syncrunner.cpp @ 1149 ) "Error uploading note:android.os.Build" 
 INFO 2017-07-01 18:45:27.648 ( nixnote.cpp @ 1880 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Error processing document: Invalid a href attribute:../../java/lang/Object.html" 
 INFO 2017-07-01 18:45:27.648 ( nixnote.cpp @ 1880 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Error processing document: Invalid a href attribute:../../java/lang/Object.html"

When i remove the formated html text, the note will sync successful

The attachment is the source code of the note.

[SourceCodeOfTheNote.txt](https://github.com/baumgarr/nixnote2/files/1117011/SourceCodeOfTheNote.txt)

**Comment by artmg** [comment] 2017-07-03 19:58
This is a duplicate of issue #294 and a known issue.

Nixnote cannot always handle pasting formatted text, especially from web pages. Please paste into a new note using 

Edit / Paste as Unformatted Text (SHFT-CTRL-P)

Then remove the old note giving the errors
Thanks

**Closed** 2017-07-24 18:15 UTC
