### ISSUE TITLE
Data_conflict parameter=Tag.name

### ISSUE THREAD

**Issue by ilpepe** [baumgarr/nixnote2#147] opened 2016-01-13 12:52 UTC
Hi, 
Like the program.
awesome Linux client.

However I continously run into tag.name errors.
'
 INFO 2016-01-13 13:48:16.058 ( nixnote.cpp @ 1790 ) "Beginning Sync" 
ERROR 2016-01-13 13:48:16.744 ( communication/communicationmanager.cpp @ 399 ) EDAMUserException: 10 

ERROR 2016-01-13 13:48:16.745 ( communication/communicationmanager.cpp @ 400 ) Tag name: "XXXX XXXX" 

 INFO 2016-01-13 13:48:16.752 ( nixnote.cpp @ 1790 ) "Communication Error - Data conflict : :EDAMUserException: DATA_CONFLICT parameter=Tag.name" 
 INFO 2016-01-13 13:48:17.371 ( nixnote.cpp @ 1790 ) "Communication Error - Data conflict : :EDAMUserException: DATA_CONFLICT parameter=Tag.name" 
'

Which I don't get using the official client under Windows.
The error is generated by evernote, I got that far, but why isn't this error in the windows app?

**Comment by baumgarr** [comment] 2016-01-13 13:12
Try renaming the tag & syncing.  My guess is that NixNote is trying to create a tag with the same name as one that already exists.

**Comment by jamiedow** [comment] 2016-01-18 09:07
Baumgarr, I'm also getting a load of conflicts that seem to be related to tags, and my hunch is that the issue is the one you're diagnosing in ilpepe's situation above.

So, the question is - why do some tags create problems? Is there some naming convention issue (using spaces? using capital letters? or something?) that makes a tag liable to generate sync issues?

What I find is that I get duplicate notes generated, and quite often the original note will have one or more blank tags on it. There is also (I *think*) inconsistency as to whether the most up-to-date note will be the one in the original notebook, or one of the ones in the conflict notebook.

I now have notebooks named "Conflict", "Conflict-1" and "Conflict-2". This is getting annoying.

Diagnosis is all very well, and vital, but can I ask if you have any guidance as to how to *avoid* these conflicts? Many thanks.

**Comment by baumgarr** [comment] 2016-01-18 13:07
Nope.  If I can't recreate it I can't diagnose it. 

The conflict-1 & conflict-2 should only happen if the note was updated on both Evernote's servers and within NixNote.

**Comment by ilpepe** [comment] 2016-01-18 13:39
Hi,
And could you give us some pointers were to look?

Almost every time I add a new tag, it is faulty....
It is hardly practical to change every new tag...

Best regards,
Pieter

**Comment by baumgarr** [comment] 2016-01-18 13:49
- What version of NixNote are you using?

- How was the tag created?  Was it created by adding it when specifying a note tag or via right-clicking the tag list & choosing "Add".

- Are you assigning the tag to a note that is in a notebook that is owned by another account or is shared to another account?

- Have you checked your Evernote account via the web interface to see if the tags it is complaining about actually exist or are being created despite the error?

- Is there anything unusual with some of the tag names it is complaining about?  Maybe a - or a . or a @ or a space in the name?

- Does the tag being created have a parent?  Is that parent also new?

**Comment by ilpepe** [comment] 2016-01-18 14:02
Hi

Thx for the reply

-> version: 2.0-beta7
-> These tags are auto created by mailing it to the inbox specific mail adres. From Thunderbird, I forward the necessary mails to evernote. The "To:" and "CC:" mail adresses are out converted to a tag when forwarding it.
-> no, all in my own account.
-> never got a complaint from the web version nor the windows client... Can you see the logs on the web server somehow?
-> There is a space in the tag (as is are names and surnames)
-> newly created tags don't have a parent, but I move them to a parent with the name ".Who"...


hope this helps?

**Comment by jamiedow** [comment] 2016-01-18 14:17
Mine seems to be syncing ok now. I deleted the blank tags that had been mysteriously generated in the processes that had given rise to the conflict notebooks. I renamed the tags I wanted to retain.
But I confess I'm not at all sure if this is what made the difference. It all seems mysterious to me.

I wonder if  - could this be plausible? - the safest way to add new tags in Nixnote is to add them from the sidebar, without their being assigned to a note, sync, and then - once the tag has synced successfully to the EN server - only then use it in notes.
I wonder if that might reduce the incidence of conflicts.

Thanks for all the help, and for the software. It's all very much appreciated.

(I'm running 2.0-beta6, btw - maybe I should upgrade?)

**Comment by baumgarr** [comment] 2016-01-18 15:03
jamiedow:

I'm glad it is working.  I'm trying to figure out a pattern to the problem but so far I haven't found a root cause.  I don't think there is anything different in beta-7 that will address the issue but I always recommend people upgrade to the latest version.  Sometimes it is corrected in a newer version & I just don't remember fixing it or I got lucky & fixed it by accident.  Regardless, it is easier to trace the messages because the line numbers haven't changed as much.

ilpepe:
Are you saying that the tag it is complaining about was downloaded from Evernote and was not created within NixNote?

**Comment by ilpepe** [comment] 2016-01-18 15:19
It was created in nixnote...
I was wrong...

I've deleted the tag, remade it, still no solution...

When I sync, it now generates empty tags. I can remove them, but everytime I sync, blank tags are generated...

Best regards,

**Comment by ilpepe** [comment] 2016-01-18 15:21
BTW, this tag is not mentioned in the evernote activity log in the windows client...

**Comment by baumgarr** [comment] 2016-01-18 15:24
Ok.  So do you know if the tag was created by adding it to the note or was it created by right-clicking on the tag list & choosing "Add"?

**Comment by ilpepe** [comment] 2016-01-18 15:26
Hi,
I think it was added in the note directly...

Do you suggest to do it the other way around next time?
And first put it under the parent before adding it to the note?

best regards,
Pieter

**Comment by baumgarr** [comment] 2016-01-18 15:33
It shouldn't matter.

Next dumb question:  You said a bunch of empty tags are created.  Are they created in the note or the tag list?  If ti is adding it to a note, could you export it and attach it so I can take a look at it?

**Comment by ilpepe** [comment] 2016-01-18 15:37
They are created in the note...

Are deleted the interfering tag, the one that generated the issue.

Maybe I'm just doing something utterly stupid...

**Comment by baumgarr** [comment] 2016-01-18 17:06
More likely you are doing something correct and the program is doing something utterly stupid.  I just wish I could recreate it.

**Comment by baumgarr** [comment] 2016-01-18 17:50
Woohoo!  I was able to recreate it.

Now I just need to figure out how I did it...

**Comment by ilpepe** [comment] 2016-01-18 19:17
Thx a lot!
Good luck with the fixing, and again awesome software!

Woohoo! I was able to recreate it.

Now I just need to figure out how I did it...

—
Reply to this email directly or view it on GitHub
<https://github.com/baumgarr/nixnote2/issues/147#issuecomment-172604460>.

**Comment by baumgarr** [comment] 2016-01-18 20:34
I think I have it fixed.

You can build it from the GitHub source or you can wait for the next beta, but there may be some things you need to do to fully correct the problem.

The tag name error should correct itself.  I had to add a little more overhead to correct it, so when the next beta comes out please upgrad.  I may remove the workaround in some future update to reduce the overhead, but once you upgrade to the next beta & do a sync the problem should be fixed permanently so it won't be needed beyond the next beta.

The other part of the problem is where notes have a tag with no name assigned to them.  Depending upon the note, it may be self-correcting after you do a sync & restart NixNote.

For the notes that it isn't self correcting there is no easy way to correct that automatically without a lot of overhead.  The easiest thing to do is to add a new tag to the note in the web interface.  That will trigger a download and a fresh update.  Hopefully this is a minority of notes.

If this isn't corrected after the next release, please re-open this issue.

Thanks for the help in debugging!

**Closed by baumgarr** 2016-01-18 20:34 UTC

**Comment by ilpepe** [comment] 2016-01-20 10:06
Thank you for the software and the fast debugging!
I might give compiling it a shot, however for a non expert, that is not 
too trivial :-s.

**Comment by baumgarr** [comment] 2016-01-20 13:46
It isn't the easiest thing to build, but there are instructions in the user manual.  You can find it under the Help menu.

**Comment by jhf2442** [comment] 2016-01-20 22:06
@ilpepe : for compiling (besides the required packages) you should have a look at the arch linux package : https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nixnote2-git
