### ISSUE TITLE
Notes with strikethrough doesn't sync with Evernote

### ISSUE THREAD

**Issue by magdmartin** [baumgarr/nixnote2#160] opened 2016-02-24 15:37 UTC
Using NixNote 2.0-beta6 on ubuntu 12.04 LTS with Evernote sync. 

Each time I use the strikethrough format in NixNote, it refuse to sync with evernote and return the following error message: 

` INFO 2016-02-24 10:30:04.896 ( nixnote.cpp @ 1775 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Attribute "class" must be declared for element type "span"." `

I had the error with several different notes in different notebooks. 
Removing the strikethrough formatting in the note fix the issue.

**Comment by hadim** [comment] 2016-02-26 21:35
Same here !

**Comment by MetaMemoryT** [comment] 2016-04-13 16:14
I am getting similar error:

```
 INFO 2016-04-13 11:09:49.449 ( nixnote.cpp @ 1790 ) "Beginning Sync" 
ERROR 2016-04-13 11:09:50.250 ( communication/communicationmanager.cpp @ 486 ) EDAMNotFoundException 
ERROR 2016-04-13 11:09:50.253 ( communication/communicationmanager.cpp @ 1182 ) EDAMNotFoundException: 

 INFO 2016-04-13 11:09:50.255 ( nixnote.cpp @ 1790 ) "EDAMNotFoundException: Note not found:EDAMNotFoundException:  identifier=Notebook.guid key=b0e16bc5-85aa-4290-bc92-d5d1b05a6bdd" 
ERROR 2016-04-13 11:09:50.451 ( communication/communicationmanager.cpp @ 548 ) EDAMUserException: 11 
 INFO 2016-04-13 11:09:50.453 ( nixnote.cpp @ 1790 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Attribute "class" must be declared for element type "span"." 
 INFO 2016-04-13 11:09:50.454 ( nixnote.cpp @ 1790 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Attribute "class" must be declared for element type "span"." 
```

I am using sqlite browser to try and hunt down the offending data, so that I can delete it

select * from datastore where data = 'b0e16bc5-85aa-4290-bc92-d5d1b05a6bdd'

lid = 1013
key = 3000
data = 

how can I relate this data I found back to the offending note?

**Comment by baumgarr** [comment] 2016-07-16 17:53
Duplicate of issue #171.

**Closed by baumgarr** 2016-07-16 17:53 UTC
